// Blocked ad/tracker domain patterns
// Electron intercepts ALL network requests and silently kills anything matching these
const BLOCKED_DOMAINS = [
  // Major ad networks
  'doubleclick.net',
  'googlesyndication.com',
  'googleadservices.com',
  'google-analytics.com',
  'googletagmanager.com',
  'googletagservices.com',
  'adservice.google.com',
  'pagead2.googlesyndication.com',

  // Popup / popunder networks
  'popads.net',
  'popcash.net',
  'popunder.net',
  'propellerads.com',
  'propellerads.net',
  'popmyads.com',
  'richpops.com',
  'clickadu.com',
  'clickadilla.com',
  'hilltopads.net',
  'hilltopads.com',
  'exoclick.com',
  'exosrv.com',
  'juicyads.com',
  'trafficjunky.com',
  'trafficfactory.biz',
  'tsyndicate.com',
  'a-ads.com',

  // Tracking & fingerprinting
  'facebook.net',
  'facebook.com/tr',
  'connect.facebook.net',
  'analytics.tiktok.com',
  'sc-static.net',
  'hotjar.com',
  'clarity.ms',
  'mouseflow.com',
  'fullstory.com',
  'crazyegg.com',
  'quantserve.com',
  'scorecardresearch.com',
  'bluekai.com',
  'krxd.net',
  'casalemedia.com',
  'moatads.com',

  // Streaming-specific ad injectors
  'streamads.net',
  'vidcloud.co/ads',
  'rabbitstream.net/ads',
  'filemoon.sx/ads',
  'mixdrop.co/ads',
  'upstream.to/ads',
  'doodstream.com/ads',
  'voe.sx/ads',

  // Generic ad/malware domains
  'adnxs.com',
  'adsrvr.org',
  'adtechus.com',
  'advertising.com',
  'taboola.com',
  'outbrain.com',
  'revcontent.com',
  'mgid.com',
  'zedo.com',
  'rubiconproject.com',
  'pubmatic.com',
  'openx.net',
  'indexexchange.com',
  'criteo.com',
  'criteo.net',
  'amazon-adsystem.com',
  'media.net',
  'yieldmo.com',
  'sharethrough.com',
  'ad.doubleclick.net',

  // Notification spam / push scams
  'onesignal.com',
  'pushwoosh.com',
  'pushcrew.com',
  'pushengage.com',
  'subscribers.com',
  'notix.io',
  'gravitec.net',
];

export default BLOCKED_DOMAINS;
